/* tslint:disable */
/* eslint-disable */
/**
 * Department Assignments API
 * Department assignments of hospital staff (assignment of employees to ambulances and hospital departments) for the Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DepartmentAssignment,
} from '../models';
import {
    DepartmentAssignmentFromJSON,
    DepartmentAssignmentToJSON,
} from '../models';

export interface CreateDepartmentAssignmentRequest {
    departmentAssignment: DepartmentAssignment;
}

export interface DeleteDepartmentAssignmentRequest {
    assignmentId: number;
}

export interface GetDepartmentAssignmentRequest {
    assignmentId: number;
}

export interface ListDepartmentAssignmentsRequest {
    employeeId?: string;
    departmentId?: string;
    activeOn?: Date;
}

export interface UpdateDepartmentAssignmentRequest {
    assignmentId: number;
    departmentAssignment: DepartmentAssignment;
}

/**
 * DepartmentAssignmentsApi - interface
 *
 * @export
 * @interface DepartmentAssignmentsApiInterface
 */
export interface DepartmentAssignmentsApiInterface {
    createDepartmentAssignmentRaw(requestParameters: CreateDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentAssignment>>;
    createDepartmentAssignment(requestParameters: CreateDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentAssignment>;
    deleteDepartmentAssignmentRaw(requestParameters: DeleteDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;
    deleteDepartmentAssignment(requestParameters: DeleteDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
    getDepartmentAssignmentRaw(requestParameters: GetDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentAssignment>>;
    getDepartmentAssignment(requestParameters: GetDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentAssignment>;
    listDepartmentAssignmentsRaw(requestParameters: ListDepartmentAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DepartmentAssignment>>>;
    listDepartmentAssignments(requestParameters: ListDepartmentAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DepartmentAssignment>>;
    updateDepartmentAssignmentRaw(requestParameters: UpdateDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentAssignment>>;
    updateDepartmentAssignment(requestParameters: UpdateDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentAssignment>;
}

export class DepartmentAssignmentsApi extends runtime.BaseAPI implements DepartmentAssignmentsApiInterface {

    async createDepartmentAssignmentRaw(requestParameters: CreateDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentAssignment>> {
        if (requestParameters.departmentAssignment === null || requestParameters.departmentAssignment === undefined) {
            throw new runtime.RequiredError('departmentAssignment','Required parameter requestParameters.departmentAssignment was null or undefined when calling createDepartmentAssignment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/department-assignments`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DepartmentAssignmentToJSON(requestParameters.departmentAssignment),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentAssignmentFromJSON(jsonValue));
    }

    async createDepartmentAssignment(requestParameters: CreateDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentAssignment> {
        const response = await this.createDepartmentAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    async deleteDepartmentAssignmentRaw(requestParameters: DeleteDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.assignmentId === null || requestParameters.assignmentId === undefined) {
            throw new runtime.RequiredError('assignmentId','Required parameter requestParameters.assignmentId was null or undefined when calling deleteDepartmentAssignment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/department-assignments/{assignmentId}`.replace(`{${"assignmentId"}}`, encodeURIComponent(String(requestParameters.assignmentId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    async deleteDepartmentAssignment(requestParameters: DeleteDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDepartmentAssignmentRaw(requestParameters, initOverrides);
    }

    async getDepartmentAssignmentRaw(requestParameters: GetDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentAssignment>> {
        if (requestParameters.assignmentId === null || requestParameters.assignmentId === undefined) {
            throw new runtime.RequiredError('assignmentId','Required parameter requestParameters.assignmentId was null or undefined when calling getDepartmentAssignment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/department-assignments/{assignmentId}`.replace(`{${"assignmentId"}}`, encodeURIComponent(String(requestParameters.assignmentId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentAssignmentFromJSON(jsonValue));
    }

    async getDepartmentAssignment(requestParameters: GetDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentAssignment> {
        const response = await this.getDepartmentAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    async listDepartmentAssignmentsRaw(requestParameters: ListDepartmentAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DepartmentAssignment>>> {
        const queryParameters: any = {};

        if (requestParameters.employeeId !== undefined) {
            queryParameters['employeeId'] = requestParameters.employeeId;
        }

        if (requestParameters.departmentId !== undefined) {
            queryParameters['departmentId'] = requestParameters.departmentId;
        }

        if (requestParameters.activeOn !== undefined) {
            queryParameters['activeOn'] = (requestParameters.activeOn as any).toISOString().substr(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/department-assignments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DepartmentAssignmentFromJSON));
    }

    async listDepartmentAssignments(requestParameters: ListDepartmentAssignmentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DepartmentAssignment>> {
        const response = await this.listDepartmentAssignmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    async updateDepartmentAssignmentRaw(requestParameters: UpdateDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentAssignment>> {
        if (requestParameters.assignmentId === null || requestParameters.assignmentId === undefined) {
            throw new runtime.RequiredError('assignmentId','Required parameter requestParameters.assignmentId was null or undefined when calling updateDepartmentAssignment.');
        }

        if (requestParameters.departmentAssignment === null || requestParameters.departmentAssignment === undefined) {
            throw new runtime.RequiredError('departmentAssignment','Required parameter requestParameters.departmentAssignment was null or undefined when calling updateDepartmentAssignment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/department-assignments/{assignmentId}`.replace(`{${"assignmentId"}}`, encodeURIComponent(String(requestParameters.assignmentId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DepartmentAssignmentToJSON(requestParameters.departmentAssignment),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentAssignmentFromJSON(jsonValue));
    }

    async updateDepartmentAssignment(requestParameters: UpdateDepartmentAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentAssignment> {
        const response = await this.updateDepartmentAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
