/* tslint:disable */
/* eslint-disable */
/**
 * Department Assignments API
 * Department assignments of hospital staff (assignment of employees to ambulances and hospital departments) for the Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DepartmentAssignment
 */
export interface DepartmentAssignment {
    /**
     * Server-assigned unique identifier
     * @type {number}
     * @memberof DepartmentAssignment
     */
    readonly id?: number;
    /**
     * Employee identifier (badge or HR id)
     * @type {string}
     * @memberof DepartmentAssignment
     */
    employeeId?: string;
    /**
     * Full name of the employee
     * @type {string}
     * @memberof DepartmentAssignment
     */
    employeeName: string;
    /**
     * Department identifier
     * @type {string}
     * @memberof DepartmentAssignment
     */
    departmentId?: string;
    /**
     * Human-readable department / ambulance name
     * @type {string}
     * @memberof DepartmentAssignment
     */
    departmentName: string;
    /**
     * Role of the employee within the department
     * @type {string}
     * @memberof DepartmentAssignment
     */
    role?: string;
    /**
     * First day of the assignment (ISO 8601)
     * @type {Date}
     * @memberof DepartmentAssignment
     */
    fromDate: Date;
    /**
     * Last day of the assignment (ISO 8601). Empty / omitted means the assignment is currently active.
     * @type {Date}
     * @memberof DepartmentAssignment
     */
    toDate?: Date;
    /**
     * Optional free-text note
     * @type {string}
     * @memberof DepartmentAssignment
     */
    note?: string;
}

/**
 * Check if a given object implements the DepartmentAssignment interface.
 */
export function instanceOfDepartmentAssignment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "employeeName" in value;
    isInstance = isInstance && "departmentName" in value;
    isInstance = isInstance && "fromDate" in value;

    return isInstance;
}

export function DepartmentAssignmentFromJSON(json: any): DepartmentAssignment {
    return DepartmentAssignmentFromJSONTyped(json, false);
}

export function DepartmentAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentAssignment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': !exists(json, 'id') ? undefined : json['id'],
        'employeeId': !exists(json, 'employeeId') ? undefined : json['employeeId'],
        'employeeName': json['employeeName'],
        'departmentId': !exists(json, 'departmentId') ? undefined : json['departmentId'],
        'departmentName': json['departmentName'],
        'role': !exists(json, 'role') ? undefined : json['role'],
        'fromDate': (new Date(json['fromDate'])),
        'toDate': !exists(json, 'toDate') ? undefined : (new Date(json['toDate'])),
        'note': !exists(json, 'note') ? undefined : json['note'],
    };
}

export function DepartmentAssignmentToJSON(value?: DepartmentAssignment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'employeeId': value.employeeId,
        'employeeName': value.employeeName,
        'departmentId': value.departmentId,
        'departmentName': value.departmentName,
        'role': value.role,
        'fromDate': (value.fromDate.toISOString().substr(0,10)),
        'toDate': value.toDate === undefined ? undefined : (value.toDate.toISOString().substr(0,10)),
        'note': value.note,
    };
}
