/* tslint:disable */
/* eslint-disable */
/**
 * Evidencia Výkonov API
 * Evidencia výkonov zamestnancov nemocnice (Performance records of hospital staff) for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  VykonZaznam,
} from '../models';
import {
    VykonZaznamFromJSON,
    VykonZaznamToJSON,
} from '../models';

export interface CreateVykonRequest {
    vykonZaznam: VykonZaznam;
}

export interface DeleteVykonRequest {
    vykonId: number;
}

export interface GetVykonRequest {
    vykonId: number;
}

export interface GetVykonListRequest {
    zamestnanecId?: string;
    from?: Date;
    to?: Date;
}

export interface UpdateVykonRequest {
    vykonId: number;
    vykonZaznam: VykonZaznam;
}

/**
 * EvidenciaVykonovApi - interface
 * 
 * @export
 * @interface EvidenciaVykonovApiInterface
 */
export interface EvidenciaVykonovApiInterface {
    /**
     * 
     * @summary Create a new performance record
     * @param {VykonZaznam} vykonZaznam Performance record to create. The &#x60;id&#x60; field is assigned by the server and ignored if provided.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EvidenciaVykonovApiInterface
     */
    createVykonRaw(requestParameters: CreateVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VykonZaznam>>;

    /**
     * Create a new performance record
     */
    createVykon(requestParameters: CreateVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VykonZaznam>;

    /**
     * 
     * @summary Delete (archive) a performance record
     * @param {number} vykonId Unique identifier of the performance record
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EvidenciaVykonovApiInterface
     */
    deleteVykonRaw(requestParameters: DeleteVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete (archive) a performance record
     */
    deleteVykon(requestParameters: DeleteVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get a single performance record by id
     * @param {number} vykonId Unique identifier of the performance record
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EvidenciaVykonovApiInterface
     */
    getVykonRaw(requestParameters: GetVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VykonZaznam>>;

    /**
     * Get a single performance record by id
     */
    getVykon(requestParameters: GetVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VykonZaznam>;

    /**
     * Returns all performance records, optionally filtered by date range or employee.
     * @summary List performance records
     * @param {string} [zamestnanecId] Filter by employee identifier
     * @param {Date} [from] Include records on or after this date (ISO 8601, yyyy-MM-dd)
     * @param {Date} [to] Include records on or before this date (ISO 8601, yyyy-MM-dd)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EvidenciaVykonovApiInterface
     */
    getVykonListRaw(requestParameters: GetVykonListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VykonZaznam>>>;

    /**
     * Returns all performance records, optionally filtered by date range or employee.
     * List performance records
     */
    getVykonList(requestParameters: GetVykonListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VykonZaznam>>;

    /**
     * 
     * @summary Update an existing performance record
     * @param {number} vykonId Unique identifier of the performance record
     * @param {VykonZaznam} vykonZaznam Updated record. Path &#x60;vykonId&#x60; takes precedence over any &#x60;id&#x60; in the body.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EvidenciaVykonovApiInterface
     */
    updateVykonRaw(requestParameters: UpdateVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VykonZaznam>>;

    /**
     * Update an existing performance record
     */
    updateVykon(requestParameters: UpdateVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VykonZaznam>;

}

/**
 * 
 */
export class EvidenciaVykonovApi extends runtime.BaseAPI implements EvidenciaVykonovApiInterface {

    /**
     * Create a new performance record
     */
    async createVykonRaw(requestParameters: CreateVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VykonZaznam>> {
        if (requestParameters.vykonZaznam === null || requestParameters.vykonZaznam === undefined) {
            throw new runtime.RequiredError('vykonZaznam','Required parameter requestParameters.vykonZaznam was null or undefined when calling createVykon.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/vykon`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VykonZaznamToJSON(requestParameters.vykonZaznam),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VykonZaznamFromJSON(jsonValue));
    }

    /**
     * Create a new performance record
     */
    async createVykon(requestParameters: CreateVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VykonZaznam> {
        const response = await this.createVykonRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete (archive) a performance record
     */
    async deleteVykonRaw(requestParameters: DeleteVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.vykonId === null || requestParameters.vykonId === undefined) {
            throw new runtime.RequiredError('vykonId','Required parameter requestParameters.vykonId was null or undefined when calling deleteVykon.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/vykon/{vykonId}`.replace(`{${"vykonId"}}`, encodeURIComponent(String(requestParameters.vykonId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete (archive) a performance record
     */
    async deleteVykon(requestParameters: DeleteVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteVykonRaw(requestParameters, initOverrides);
    }

    /**
     * Get a single performance record by id
     */
    async getVykonRaw(requestParameters: GetVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VykonZaznam>> {
        if (requestParameters.vykonId === null || requestParameters.vykonId === undefined) {
            throw new runtime.RequiredError('vykonId','Required parameter requestParameters.vykonId was null or undefined when calling getVykon.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/vykon/{vykonId}`.replace(`{${"vykonId"}}`, encodeURIComponent(String(requestParameters.vykonId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VykonZaznamFromJSON(jsonValue));
    }

    /**
     * Get a single performance record by id
     */
    async getVykon(requestParameters: GetVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VykonZaznam> {
        const response = await this.getVykonRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all performance records, optionally filtered by date range or employee.
     * List performance records
     */
    async getVykonListRaw(requestParameters: GetVykonListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VykonZaznam>>> {
        const queryParameters: any = {};

        if (requestParameters.zamestnanecId !== undefined) {
            queryParameters['zamestnanecId'] = requestParameters.zamestnanecId;
        }

        if (requestParameters.from !== undefined) {
            queryParameters['from'] = (requestParameters.from as any).toISOString().substr(0,10);
        }

        if (requestParameters.to !== undefined) {
            queryParameters['to'] = (requestParameters.to as any).toISOString().substr(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/vykon`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VykonZaznamFromJSON));
    }

    /**
     * Returns all performance records, optionally filtered by date range or employee.
     * List performance records
     */
    async getVykonList(requestParameters: GetVykonListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VykonZaznam>> {
        const response = await this.getVykonListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing performance record
     */
    async updateVykonRaw(requestParameters: UpdateVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VykonZaznam>> {
        if (requestParameters.vykonId === null || requestParameters.vykonId === undefined) {
            throw new runtime.RequiredError('vykonId','Required parameter requestParameters.vykonId was null or undefined when calling updateVykon.');
        }

        if (requestParameters.vykonZaznam === null || requestParameters.vykonZaznam === undefined) {
            throw new runtime.RequiredError('vykonZaznam','Required parameter requestParameters.vykonZaznam was null or undefined when calling updateVykon.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/vykon/{vykonId}`.replace(`{${"vykonId"}}`, encodeURIComponent(String(requestParameters.vykonId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VykonZaznamToJSON(requestParameters.vykonZaznam),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VykonZaznamFromJSON(jsonValue));
    }

    /**
     * Update an existing performance record
     */
    async updateVykon(requestParameters: UpdateVykonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VykonZaznam> {
        const response = await this.updateVykonRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
