/* tslint:disable */
/* eslint-disable */
/**
 * Performance Records API
 * Performance records of hospital staff (worked hours, examinations, operations, on-call shifts) for the Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PerformanceRecord,
} from '../models';
import {
    PerformanceRecordFromJSON,
    PerformanceRecordToJSON,
} from '../models';

export interface CreatePerformanceRecordRequest {
    performanceRecord: PerformanceRecord;
}

export interface DeletePerformanceRecordRequest {
    recordId: number;
}

export interface GetPerformanceRecordRequest {
    recordId: number;
}

export interface ListPerformanceRecordsRequest {
    employeeId?: string;
    from?: Date;
    to?: Date;
}

export interface UpdatePerformanceRecordRequest {
    recordId: number;
    performanceRecord: PerformanceRecord;
}

/**
 * PerformanceRecordsApi - interface
 *
 * @export
 * @interface PerformanceRecordsApiInterface
 */
export interface PerformanceRecordsApiInterface {
    /**
     *
     * @summary Create a new performance record
     */
    createPerformanceRecordRaw(requestParameters: CreatePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformanceRecord>>;

    /**
     * Create a new performance record
     */
    createPerformanceRecord(requestParameters: CreatePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformanceRecord>;

    /**
     *
     * @summary Delete (archive) a performance record
     */
    deletePerformanceRecordRaw(requestParameters: DeletePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete (archive) a performance record
     */
    deletePerformanceRecord(requestParameters: DeletePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     *
     * @summary Get a single performance record by id
     */
    getPerformanceRecordRaw(requestParameters: GetPerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformanceRecord>>;

    /**
     * Get a single performance record by id
     */
    getPerformanceRecord(requestParameters: GetPerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformanceRecord>;

    /**
     * Returns all performance records, optionally filtered by date range or employee.
     * @summary List performance records
     */
    listPerformanceRecordsRaw(requestParameters: ListPerformanceRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PerformanceRecord>>>;

    /**
     * Returns all performance records, optionally filtered by date range or employee.
     * List performance records
     */
    listPerformanceRecords(requestParameters: ListPerformanceRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PerformanceRecord>>;

    /**
     *
     * @summary Update an existing performance record
     */
    updatePerformanceRecordRaw(requestParameters: UpdatePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformanceRecord>>;

    /**
     * Update an existing performance record
     */
    updatePerformanceRecord(requestParameters: UpdatePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformanceRecord>;
}

/**
 *
 */
export class PerformanceRecordsApi extends runtime.BaseAPI implements PerformanceRecordsApiInterface {

    /**
     * Create a new performance record
     */
    async createPerformanceRecordRaw(requestParameters: CreatePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformanceRecord>> {
        if (requestParameters.performanceRecord === null || requestParameters.performanceRecord === undefined) {
            throw new runtime.RequiredError('performanceRecord','Required parameter requestParameters.performanceRecord was null or undefined when calling createPerformanceRecord.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/performance-records`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PerformanceRecordToJSON(requestParameters.performanceRecord),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerformanceRecordFromJSON(jsonValue));
    }

    /**
     * Create a new performance record
     */
    async createPerformanceRecord(requestParameters: CreatePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformanceRecord> {
        const response = await this.createPerformanceRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete (archive) a performance record
     */
    async deletePerformanceRecordRaw(requestParameters: DeletePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.recordId === null || requestParameters.recordId === undefined) {
            throw new runtime.RequiredError('recordId','Required parameter requestParameters.recordId was null or undefined when calling deletePerformanceRecord.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/performance-records/{recordId}`.replace(`{${"recordId"}}`, encodeURIComponent(String(requestParameters.recordId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete (archive) a performance record
     */
    async deletePerformanceRecord(requestParameters: DeletePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePerformanceRecordRaw(requestParameters, initOverrides);
    }

    /**
     * Get a single performance record by id
     */
    async getPerformanceRecordRaw(requestParameters: GetPerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformanceRecord>> {
        if (requestParameters.recordId === null || requestParameters.recordId === undefined) {
            throw new runtime.RequiredError('recordId','Required parameter requestParameters.recordId was null or undefined when calling getPerformanceRecord.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/performance-records/{recordId}`.replace(`{${"recordId"}}`, encodeURIComponent(String(requestParameters.recordId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerformanceRecordFromJSON(jsonValue));
    }

    /**
     * Get a single performance record by id
     */
    async getPerformanceRecord(requestParameters: GetPerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformanceRecord> {
        const response = await this.getPerformanceRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all performance records, optionally filtered by date range or employee.
     * List performance records
     */
    async listPerformanceRecordsRaw(requestParameters: ListPerformanceRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PerformanceRecord>>> {
        const queryParameters: any = {};

        if (requestParameters.employeeId !== undefined) {
            queryParameters['employeeId'] = requestParameters.employeeId;
        }

        if (requestParameters.from !== undefined) {
            queryParameters['from'] = (requestParameters.from as any).toISOString().substr(0,10);
        }

        if (requestParameters.to !== undefined) {
            queryParameters['to'] = (requestParameters.to as any).toISOString().substr(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/performance-records`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PerformanceRecordFromJSON));
    }

    /**
     * Returns all performance records, optionally filtered by date range or employee.
     * List performance records
     */
    async listPerformanceRecords(requestParameters: ListPerformanceRecordsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PerformanceRecord>> {
        const response = await this.listPerformanceRecordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing performance record
     */
    async updatePerformanceRecordRaw(requestParameters: UpdatePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformanceRecord>> {
        if (requestParameters.recordId === null || requestParameters.recordId === undefined) {
            throw new runtime.RequiredError('recordId','Required parameter requestParameters.recordId was null or undefined when calling updatePerformanceRecord.');
        }

        if (requestParameters.performanceRecord === null || requestParameters.performanceRecord === undefined) {
            throw new runtime.RequiredError('performanceRecord','Required parameter requestParameters.performanceRecord was null or undefined when calling updatePerformanceRecord.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/performance-records/{recordId}`.replace(`{${"recordId"}}`, encodeURIComponent(String(requestParameters.recordId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PerformanceRecordToJSON(requestParameters.performanceRecord),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerformanceRecordFromJSON(jsonValue));
    }

    /**
     * Update an existing performance record
     */
    async updatePerformanceRecord(requestParameters: UpdatePerformanceRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformanceRecord> {
        const response = await this.updatePerformanceRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
