/* tslint:disable */
/* eslint-disable */
/**
 * Evidencia Výkonov API
 * Evidencia výkonov zamestnancov nemocnice (Performance records of hospital staff) for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VykonZaznam
 */
export interface VykonZaznam {
    /**
     * Server-assigned unique identifier
     * @type {number}
     * @memberof VykonZaznam
     */
    readonly id?: number;
    /**
     * Employee identifier (badge or HR id)
     * @type {string}
     * @memberof VykonZaznam
     */
    zamestnanecId?: string;
    /**
     * Full name of the employee
     * @type {string}
     * @memberof VykonZaznam
     */
    zamestnanecMeno: string;
    /**
     * Date the work was performed (ISO 8601)
     * @type {Date}
     * @memberof VykonZaznam
     */
    datum: Date;
    /**
     * Hours worked on this date
     * @type {number}
     * @memberof VykonZaznam
     */
    odpracovaneHodiny: number;
    /**
     * Number of examinations performed
     * @type {number}
     * @memberof VykonZaznam
     */
    pocetVysetreni: number;
    /**
     * Number of operations performed
     * @type {number}
     * @memberof VykonZaznam
     */
    pocetOperacii: number;
    /**
     * Number of on-call shifts
     * @type {number}
     * @memberof VykonZaznam
     */
    pocetSluzieb: number;
    /**
     * Optional free-text note
     * @type {string}
     * @memberof VykonZaznam
     */
    poznamka?: string;
}

/**
 * Check if a given object implements the VykonZaznam interface.
 */
export function instanceOfVykonZaznam(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "zamestnanecMeno" in value;
    isInstance = isInstance && "datum" in value;
    isInstance = isInstance && "odpracovaneHodiny" in value;
    isInstance = isInstance && "pocetVysetreni" in value;
    isInstance = isInstance && "pocetOperacii" in value;
    isInstance = isInstance && "pocetSluzieb" in value;

    return isInstance;
}

export function VykonZaznamFromJSON(json: any): VykonZaznam {
    return VykonZaznamFromJSONTyped(json, false);
}

export function VykonZaznamFromJSONTyped(json: any, ignoreDiscriminator: boolean): VykonZaznam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'zamestnanecId': !exists(json, 'zamestnanecId') ? undefined : json['zamestnanecId'],
        'zamestnanecMeno': json['zamestnanecMeno'],
        'datum': (new Date(json['datum'])),
        'odpracovaneHodiny': json['odpracovaneHodiny'],
        'pocetVysetreni': json['pocetVysetreni'],
        'pocetOperacii': json['pocetOperacii'],
        'pocetSluzieb': json['pocetSluzieb'],
        'poznamka': !exists(json, 'poznamka') ? undefined : json['poznamka'],
    };
}

export function VykonZaznamToJSON(value?: VykonZaznam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'zamestnanecId': value.zamestnanecId,
        'zamestnanecMeno': value.zamestnanecMeno,
        'datum': (value.datum.toISOString().substr(0,10)),
        'odpracovaneHodiny': value.odpracovaneHodiny,
        'pocetVysetreni': value.pocetVysetreni,
        'pocetOperacii': value.pocetOperacii,
        'pocetSluzieb': value.pocetSluzieb,
        'poznamka': value.poznamka,
    };
}

