/* tslint:disable */
/* eslint-disable */
/**
 * Employee Profiles API
 * Employee profiles of hospital staff for the Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmployeeProfile,
  EmployeeStatus,
} from '../models/index';
import {
    EmployeeProfileFromJSON,
    EmployeeProfileToJSON,
    EmployeeStatusFromJSON,
    EmployeeStatusToJSON,
} from '../models/index';

export interface ArchiveEmployeeProfileRequest {
    employeeId: number;
}

export interface CreateEmployeeProfileRequest {
    employeeProfile: Omit<EmployeeProfile, 'id'|'createdAt'|'updatedAt'|'archivedAt'>;
}

export interface GetEmployeeProfileRequest {
    employeeId: number;
}

export interface ListEmployeeProfilesRequest {
    department?: string;
    specialization?: string;
    status?: EmployeeStatus;
}

export interface UpdateEmployeeProfileRequest {
    employeeId: number;
    employeeProfile: Omit<EmployeeProfile, 'id'|'createdAt'|'updatedAt'|'archivedAt'>;
}

/**
 * EmployeeProfilesApi - interface
 * 
 * @export
 * @interface EmployeeProfilesApiInterface
 */
export interface EmployeeProfilesApiInterface {
    /**
     * Creates request options for archiveEmployeeProfile without sending the request
     * @param {number} employeeId 
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    archiveEmployeeProfileRequestOpts(requestParameters: ArchiveEmployeeProfileRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Archive an employee profile
     * @param {number} employeeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    archiveEmployeeProfileRaw(requestParameters: ArchiveEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Archive an employee profile
     */
    archiveEmployeeProfile(requestParameters: ArchiveEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for createEmployeeProfile without sending the request
     * @param {EmployeeProfile} employeeProfile 
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    createEmployeeProfileRequestOpts(requestParameters: CreateEmployeeProfileRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a new employee profile
     * @param {EmployeeProfile} employeeProfile 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    createEmployeeProfileRaw(requestParameters: CreateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>>;

    /**
     * Create a new employee profile
     */
    createEmployeeProfile(requestParameters: CreateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile>;

    /**
     * Creates request options for getEmployeeProfile without sending the request
     * @param {number} employeeId 
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    getEmployeeProfileRequestOpts(requestParameters: GetEmployeeProfileRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a single employee profile by id
     * @param {number} employeeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    getEmployeeProfileRaw(requestParameters: GetEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>>;

    /**
     * Get a single employee profile by id
     */
    getEmployeeProfile(requestParameters: GetEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile>;

    /**
     * Creates request options for listEmployeeProfiles without sending the request
     * @param {string} [department] 
     * @param {string} [specialization] 
     * @param {EmployeeStatus} [status] 
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    listEmployeeProfilesRequestOpts(requestParameters: ListEmployeeProfilesRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns all employee profiles, optionally filtered by department, specialization, or status.
     * @summary List employee profiles
     * @param {string} [department] 
     * @param {string} [specialization] 
     * @param {EmployeeStatus} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    listEmployeeProfilesRaw(requestParameters: ListEmployeeProfilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EmployeeProfile>>>;

    /**
     * Returns all employee profiles, optionally filtered by department, specialization, or status.
     * List employee profiles
     */
    listEmployeeProfiles(requestParameters: ListEmployeeProfilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EmployeeProfile>>;

    /**
     * Creates request options for updateEmployeeProfile without sending the request
     * @param {number} employeeId 
     * @param {EmployeeProfile} employeeProfile 
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    updateEmployeeProfileRequestOpts(requestParameters: UpdateEmployeeProfileRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update an existing employee profile
     * @param {number} employeeId 
     * @param {EmployeeProfile} employeeProfile 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeProfilesApiInterface
     */
    updateEmployeeProfileRaw(requestParameters: UpdateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>>;

    /**
     * Update an existing employee profile
     */
    updateEmployeeProfile(requestParameters: UpdateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile>;

}

/**
 * 
 */
export class EmployeeProfilesApi extends runtime.BaseAPI implements EmployeeProfilesApiInterface {

    /**
     * Creates request options for archiveEmployeeProfile without sending the request
     */
    async archiveEmployeeProfileRequestOpts(requestParameters: ArchiveEmployeeProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling archiveEmployeeProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/employees/{employeeId}`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Archive an employee profile
     */
    async archiveEmployeeProfileRaw(requestParameters: ArchiveEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.archiveEmployeeProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Archive an employee profile
     */
    async archiveEmployeeProfile(requestParameters: ArchiveEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.archiveEmployeeProfileRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createEmployeeProfile without sending the request
     */
    async createEmployeeProfileRequestOpts(requestParameters: CreateEmployeeProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeProfile'] == null) {
            throw new runtime.RequiredError(
                'employeeProfile',
                'Required parameter "employeeProfile" was null or undefined when calling createEmployeeProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/employees`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeProfileToJSON(requestParameters['employeeProfile']),
        };
    }

    /**
     * Create a new employee profile
     */
    async createEmployeeProfileRaw(requestParameters: CreateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>> {
        const requestOptions = await this.createEmployeeProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeProfileFromJSON(jsonValue));
    }

    /**
     * Create a new employee profile
     */
    async createEmployeeProfile(requestParameters: CreateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile> {
        const response = await this.createEmployeeProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEmployeeProfile without sending the request
     */
    async getEmployeeProfileRequestOpts(requestParameters: GetEmployeeProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling getEmployeeProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/employees/{employeeId}`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single employee profile by id
     */
    async getEmployeeProfileRaw(requestParameters: GetEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>> {
        const requestOptions = await this.getEmployeeProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeProfileFromJSON(jsonValue));
    }

    /**
     * Get a single employee profile by id
     */
    async getEmployeeProfile(requestParameters: GetEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile> {
        const response = await this.getEmployeeProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEmployeeProfiles without sending the request
     */
    async listEmployeeProfilesRequestOpts(requestParameters: ListEmployeeProfilesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['department'] != null) {
            queryParameters['department'] = requestParameters['department'];
        }

        if (requestParameters['specialization'] != null) {
            queryParameters['specialization'] = requestParameters['specialization'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/employees`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all employee profiles, optionally filtered by department, specialization, or status.
     * List employee profiles
     */
    async listEmployeeProfilesRaw(requestParameters: ListEmployeeProfilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EmployeeProfile>>> {
        const requestOptions = await this.listEmployeeProfilesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EmployeeProfileFromJSON));
    }

    /**
     * Returns all employee profiles, optionally filtered by department, specialization, or status.
     * List employee profiles
     */
    async listEmployeeProfiles(requestParameters: ListEmployeeProfilesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EmployeeProfile>> {
        const response = await this.listEmployeeProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEmployeeProfile without sending the request
     */
    async updateEmployeeProfileRequestOpts(requestParameters: UpdateEmployeeProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling updateEmployeeProfile().'
            );
        }

        if (requestParameters['employeeProfile'] == null) {
            throw new runtime.RequiredError(
                'employeeProfile',
                'Required parameter "employeeProfile" was null or undefined when calling updateEmployeeProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/employees/{employeeId}`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeProfileToJSON(requestParameters['employeeProfile']),
        };
    }

    /**
     * Update an existing employee profile
     */
    async updateEmployeeProfileRaw(requestParameters: UpdateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeProfile>> {
        const requestOptions = await this.updateEmployeeProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeProfileFromJSON(jsonValue));
    }

    /**
     * Update an existing employee profile
     */
    async updateEmployeeProfile(requestParameters: UpdateEmployeeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeProfile> {
        const response = await this.updateEmployeeProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
