/* tslint:disable */
/* eslint-disable */
/**
 * Employee Profiles API
 * Employee profiles of hospital staff for the Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmployeeStatus } from './EmployeeStatus';
import {
    EmployeeStatusFromJSON,
    EmployeeStatusFromJSONTyped,
    EmployeeStatusToJSON,
    EmployeeStatusToJSONTyped,
} from './EmployeeStatus';

/**
 * 
 * @export
 * @interface EmployeeProfile
 */
export interface EmployeeProfile {
    /**
     * 
     * @type {number}
     * @memberof EmployeeProfile
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeProfile
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeProfile
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeProfile
     */
    birthDate: Date;
    /**
     * 
     * @type {string}
     * @memberof EmployeeProfile
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeProfile
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeProfile
     */
    position: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeProfile
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeProfile
     */
    specialization: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeProfile
     */
    qualification: string;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeProfile
     */
    employmentStartDate: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof EmployeeProfile
     */
    certificates: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EmployeeProfile
     */
    note?: string;
    /**
     * 
     * @type {EmployeeStatus}
     * @memberof EmployeeProfile
     */
    status?: EmployeeStatus;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeProfile
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeProfile
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeProfile
     */
    readonly archivedAt?: Date;
}



/**
 * Check if a given object implements the EmployeeProfile interface.
 */
export function instanceOfEmployeeProfile(value: object): value is EmployeeProfile {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('specialization' in value) || value['specialization'] === undefined) return false;
    if (!('qualification' in value) || value['qualification'] === undefined) return false;
    if (!('employmentStartDate' in value) || value['employmentStartDate'] === undefined) return false;
    if (!('certificates' in value) || value['certificates'] === undefined) return false;
    return true;
}

export function EmployeeProfileFromJSON(json: any): EmployeeProfile {
    return EmployeeProfileFromJSONTyped(json, false);
}

export function EmployeeProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'birthDate': (new Date(json['birthDate'])),
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'position': json['position'],
        'department': json['department'] == null ? undefined : json['department'],
        'specialization': json['specialization'],
        'qualification': json['qualification'],
        'employmentStartDate': (new Date(json['employmentStartDate'])),
        'certificates': json['certificates'],
        'note': json['note'] == null ? undefined : json['note'],
        'status': json['status'] == null ? undefined : EmployeeStatusFromJSON(json['status']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'archivedAt': json['archivedAt'] == null ? undefined : (new Date(json['archivedAt'])),
    };
}

export function EmployeeProfileToJSON(json: any): EmployeeProfile {
    return EmployeeProfileToJSONTyped(json, false);
}

export function EmployeeProfileToJSONTyped(value?: Omit<EmployeeProfile, 'id'|'createdAt'|'updatedAt'|'archivedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'birthDate': value['birthDate'].toISOString().substring(0,10),
        'email': value['email'],
        'phone': value['phone'],
        'position': value['position'],
        'department': value['department'],
        'specialization': value['specialization'],
        'qualification': value['qualification'],
        'employmentStartDate': value['employmentStartDate'].toISOString().substring(0,10),
        'certificates': value['certificates'],
        'note': value['note'],
        'status': EmployeeStatusToJSON(value['status']),
    };
}

