/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EmployeeProfile } from "./utils/employee-store";
export { EmployeeProfile } from "./utils/employee-store";
export namespace Components {
    interface AssignmentApp {
        /**
          * @default ''
         */
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
    }
    interface AssignmentEditor {
        /**
          * @default ''
         */
        "apiBase": string;
        "entryId": string;
    }
    interface AssignmentList {
        /**
          * @default ''
         */
        "apiBase": string;
    }
    interface EmployeeCreate {
        /**
          * @default ''
         */
        "editEmployeeId": string;
    }
    interface EmployeeList {
        /**
          * @default 0
         */
        "refreshToken": number;
    }
    interface EmployeeWorkspace {
    }
    interface MainComponent {
    }
    interface VykonApp {
        /**
          * @default ''
         */
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
    }
    interface VykonEditor {
        /**
          * @default ''
         */
        "apiBase": string;
        "entryId": string;
    }
    interface VykonList {
        /**
          * @default ''
         */
        "apiBase": string;
    }
}
export interface AssignmentEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAssignmentEditorElement;
}
export interface AssignmentListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAssignmentListElement;
}
export interface EmployeeCreateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEmployeeCreateElement;
}
export interface EmployeeListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEmployeeListElement;
}
export interface VykonEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVykonEditorElement;
}
export interface VykonListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVykonListElement;
}
declare global {
    interface HTMLAssignmentAppElement extends Components.AssignmentApp, HTMLStencilElement {
    }
    var HTMLAssignmentAppElement: {
        prototype: HTMLAssignmentAppElement;
        new (): HTMLAssignmentAppElement;
    };
    interface HTMLAssignmentEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLAssignmentEditorElement extends Components.AssignmentEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAssignmentEditorElementEventMap>(type: K, listener: (this: HTMLAssignmentEditorElement, ev: AssignmentEditorCustomEvent<HTMLAssignmentEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAssignmentEditorElementEventMap>(type: K, listener: (this: HTMLAssignmentEditorElement, ev: AssignmentEditorCustomEvent<HTMLAssignmentEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAssignmentEditorElement: {
        prototype: HTMLAssignmentEditorElement;
        new (): HTMLAssignmentEditorElement;
    };
    interface HTMLAssignmentListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLAssignmentListElement extends Components.AssignmentList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAssignmentListElementEventMap>(type: K, listener: (this: HTMLAssignmentListElement, ev: AssignmentListCustomEvent<HTMLAssignmentListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAssignmentListElementEventMap>(type: K, listener: (this: HTMLAssignmentListElement, ev: AssignmentListCustomEvent<HTMLAssignmentListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAssignmentListElement: {
        prototype: HTMLAssignmentListElement;
        new (): HTMLAssignmentListElement;
    };
    interface HTMLEmployeeCreateElementEventMap {
        "employee-created": EmployeeProfile;
        "employee-updated": EmployeeProfile;
        "employee-edit-cancelled": string;
    }
    interface HTMLEmployeeCreateElement extends Components.EmployeeCreate, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEmployeeCreateElementEventMap>(type: K, listener: (this: HTMLEmployeeCreateElement, ev: EmployeeCreateCustomEvent<HTMLEmployeeCreateElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEmployeeCreateElementEventMap>(type: K, listener: (this: HTMLEmployeeCreateElement, ev: EmployeeCreateCustomEvent<HTMLEmployeeCreateElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEmployeeCreateElement: {
        prototype: HTMLEmployeeCreateElement;
        new (): HTMLEmployeeCreateElement;
    };
    interface HTMLEmployeeListElementEventMap {
        "employee-edit-requested": string;
        "employee-archive-requested": string;
    }
    interface HTMLEmployeeListElement extends Components.EmployeeList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEmployeeListElementEventMap>(type: K, listener: (this: HTMLEmployeeListElement, ev: EmployeeListCustomEvent<HTMLEmployeeListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEmployeeListElementEventMap>(type: K, listener: (this: HTMLEmployeeListElement, ev: EmployeeListCustomEvent<HTMLEmployeeListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEmployeeListElement: {
        prototype: HTMLEmployeeListElement;
        new (): HTMLEmployeeListElement;
    };
    interface HTMLEmployeeWorkspaceElement extends Components.EmployeeWorkspace, HTMLStencilElement {
    }
    var HTMLEmployeeWorkspaceElement: {
        prototype: HTMLEmployeeWorkspaceElement;
        new (): HTMLEmployeeWorkspaceElement;
    };
    interface HTMLMainComponentElement extends Components.MainComponent, HTMLStencilElement {
    }
    var HTMLMainComponentElement: {
        prototype: HTMLMainComponentElement;
        new (): HTMLMainComponentElement;
    };
    interface HTMLVykonAppElement extends Components.VykonApp, HTMLStencilElement {
    }
    var HTMLVykonAppElement: {
        prototype: HTMLVykonAppElement;
        new (): HTMLVykonAppElement;
    };
    interface HTMLVykonEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLVykonEditorElement extends Components.VykonEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVykonEditorElementEventMap>(type: K, listener: (this: HTMLVykonEditorElement, ev: VykonEditorCustomEvent<HTMLVykonEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVykonEditorElementEventMap>(type: K, listener: (this: HTMLVykonEditorElement, ev: VykonEditorCustomEvent<HTMLVykonEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVykonEditorElement: {
        prototype: HTMLVykonEditorElement;
        new (): HTMLVykonEditorElement;
    };
    interface HTMLVykonListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLVykonListElement extends Components.VykonList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVykonListElementEventMap>(type: K, listener: (this: HTMLVykonListElement, ev: VykonListCustomEvent<HTMLVykonListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVykonListElementEventMap>(type: K, listener: (this: HTMLVykonListElement, ev: VykonListCustomEvent<HTMLVykonListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVykonListElement: {
        prototype: HTMLVykonListElement;
        new (): HTMLVykonListElement;
    };
    interface HTMLElementTagNameMap {
        "assignment-app": HTMLAssignmentAppElement;
        "assignment-editor": HTMLAssignmentEditorElement;
        "assignment-list": HTMLAssignmentListElement;
        "employee-create": HTMLEmployeeCreateElement;
        "employee-list": HTMLEmployeeListElement;
        "employee-workspace": HTMLEmployeeWorkspaceElement;
        "main-component": HTMLMainComponentElement;
        "vykon-app": HTMLVykonAppElement;
        "vykon-editor": HTMLVykonEditorElement;
        "vykon-list": HTMLVykonListElement;
    }
}
declare namespace LocalJSX {
    interface AssignmentApp {
        /**
          * @default ''
         */
        "apiBase"?: string;
        /**
          * @default ''
         */
        "basePath"?: string;
    }
    interface AssignmentEditor {
        /**
          * @default ''
         */
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: AssignmentEditorCustomEvent<string>) => void;
    }
    interface AssignmentList {
        /**
          * @default ''
         */
        "apiBase"?: string;
        "onEntry-clicked"?: (event: AssignmentListCustomEvent<string>) => void;
    }
    interface EmployeeCreate {
        /**
          * @default ''
         */
        "editEmployeeId"?: string;
        "onEmployee-created"?: (event: EmployeeCreateCustomEvent<EmployeeProfile>) => void;
        "onEmployee-edit-cancelled"?: (event: EmployeeCreateCustomEvent<string>) => void;
        "onEmployee-updated"?: (event: EmployeeCreateCustomEvent<EmployeeProfile>) => void;
    }
    interface EmployeeList {
        "onEmployee-archive-requested"?: (event: EmployeeListCustomEvent<string>) => void;
        "onEmployee-edit-requested"?: (event: EmployeeListCustomEvent<string>) => void;
        /**
          * @default 0
         */
        "refreshToken"?: number;
    }
    interface EmployeeWorkspace {
    }
    interface MainComponent {
    }
    interface VykonApp {
        /**
          * @default ''
         */
        "apiBase"?: string;
        /**
          * @default ''
         */
        "basePath"?: string;
    }
    interface VykonEditor {
        /**
          * @default ''
         */
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: VykonEditorCustomEvent<string>) => void;
    }
    interface VykonList {
        /**
          * @default ''
         */
        "apiBase"?: string;
        "onEntry-clicked"?: (event: VykonListCustomEvent<string>) => void;
    }

    interface AssignmentAppAttributes {
        "basePath": string;
        "apiBase": string;
    }
    interface AssignmentEditorAttributes {
        "entryId": string;
        "apiBase": string;
    }
    interface AssignmentListAttributes {
        "apiBase": string;
    }
    interface EmployeeCreateAttributes {
        "editEmployeeId": string;
    }
    interface EmployeeListAttributes {
        "refreshToken": number;
    }
    interface VykonAppAttributes {
        "basePath": string;
        "apiBase": string;
    }
    interface VykonEditorAttributes {
        "entryId": string;
        "apiBase": string;
    }
    interface VykonListAttributes {
        "apiBase": string;
    }

    interface IntrinsicElements {
        "assignment-app": Omit<AssignmentApp, keyof AssignmentAppAttributes> & { [K in keyof AssignmentApp & keyof AssignmentAppAttributes]?: AssignmentApp[K] } & { [K in keyof AssignmentApp & keyof AssignmentAppAttributes as `attr:${K}`]?: AssignmentAppAttributes[K] } & { [K in keyof AssignmentApp & keyof AssignmentAppAttributes as `prop:${K}`]?: AssignmentApp[K] };
        "assignment-editor": Omit<AssignmentEditor, keyof AssignmentEditorAttributes> & { [K in keyof AssignmentEditor & keyof AssignmentEditorAttributes]?: AssignmentEditor[K] } & { [K in keyof AssignmentEditor & keyof AssignmentEditorAttributes as `attr:${K}`]?: AssignmentEditorAttributes[K] } & { [K in keyof AssignmentEditor & keyof AssignmentEditorAttributes as `prop:${K}`]?: AssignmentEditor[K] };
        "assignment-list": Omit<AssignmentList, keyof AssignmentListAttributes> & { [K in keyof AssignmentList & keyof AssignmentListAttributes]?: AssignmentList[K] } & { [K in keyof AssignmentList & keyof AssignmentListAttributes as `attr:${K}`]?: AssignmentListAttributes[K] } & { [K in keyof AssignmentList & keyof AssignmentListAttributes as `prop:${K}`]?: AssignmentList[K] };
        "employee-create": Omit<EmployeeCreate, keyof EmployeeCreateAttributes> & { [K in keyof EmployeeCreate & keyof EmployeeCreateAttributes]?: EmployeeCreate[K] } & { [K in keyof EmployeeCreate & keyof EmployeeCreateAttributes as `attr:${K}`]?: EmployeeCreateAttributes[K] } & { [K in keyof EmployeeCreate & keyof EmployeeCreateAttributes as `prop:${K}`]?: EmployeeCreate[K] };
        "employee-list": Omit<EmployeeList, keyof EmployeeListAttributes> & { [K in keyof EmployeeList & keyof EmployeeListAttributes]?: EmployeeList[K] } & { [K in keyof EmployeeList & keyof EmployeeListAttributes as `attr:${K}`]?: EmployeeListAttributes[K] } & { [K in keyof EmployeeList & keyof EmployeeListAttributes as `prop:${K}`]?: EmployeeList[K] };
        "employee-workspace": EmployeeWorkspace;
        "main-component": MainComponent;
        "vykon-app": Omit<VykonApp, keyof VykonAppAttributes> & { [K in keyof VykonApp & keyof VykonAppAttributes]?: VykonApp[K] } & { [K in keyof VykonApp & keyof VykonAppAttributes as `attr:${K}`]?: VykonAppAttributes[K] } & { [K in keyof VykonApp & keyof VykonAppAttributes as `prop:${K}`]?: VykonApp[K] };
        "vykon-editor": Omit<VykonEditor, keyof VykonEditorAttributes> & { [K in keyof VykonEditor & keyof VykonEditorAttributes]?: VykonEditor[K] } & { [K in keyof VykonEditor & keyof VykonEditorAttributes as `attr:${K}`]?: VykonEditorAttributes[K] } & { [K in keyof VykonEditor & keyof VykonEditorAttributes as `prop:${K}`]?: VykonEditor[K] };
        "vykon-list": Omit<VykonList, keyof VykonListAttributes> & { [K in keyof VykonList & keyof VykonListAttributes]?: VykonList[K] } & { [K in keyof VykonList & keyof VykonListAttributes as `attr:${K}`]?: VykonListAttributes[K] } & { [K in keyof VykonList & keyof VykonListAttributes as `prop:${K}`]?: VykonList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "assignment-app": LocalJSX.IntrinsicElements["assignment-app"] & JSXBase.HTMLAttributes<HTMLAssignmentAppElement>;
            "assignment-editor": LocalJSX.IntrinsicElements["assignment-editor"] & JSXBase.HTMLAttributes<HTMLAssignmentEditorElement>;
            "assignment-list": LocalJSX.IntrinsicElements["assignment-list"] & JSXBase.HTMLAttributes<HTMLAssignmentListElement>;
            "employee-create": LocalJSX.IntrinsicElements["employee-create"] & JSXBase.HTMLAttributes<HTMLEmployeeCreateElement>;
            "employee-list": LocalJSX.IntrinsicElements["employee-list"] & JSXBase.HTMLAttributes<HTMLEmployeeListElement>;
            "employee-workspace": LocalJSX.IntrinsicElements["employee-workspace"] & JSXBase.HTMLAttributes<HTMLEmployeeWorkspaceElement>;
            "main-component": LocalJSX.IntrinsicElements["main-component"] & JSXBase.HTMLAttributes<HTMLMainComponentElement>;
            "vykon-app": LocalJSX.IntrinsicElements["vykon-app"] & JSXBase.HTMLAttributes<HTMLVykonAppElement>;
            "vykon-editor": LocalJSX.IntrinsicElements["vykon-editor"] & JSXBase.HTMLAttributes<HTMLVykonEditorElement>;
            "vykon-list": LocalJSX.IntrinsicElements["vykon-list"] & JSXBase.HTMLAttributes<HTMLVykonListElement>;
        }
    }
}
